--
-- querys para la bd
-- creación de todas las tablas:


CREATE TABLE entidad_federativa (
  id_entidad     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,		-- Identificador único
  nombre_entidad VARCHAR(50) NOT NULL UNIQUE,							-- Nombre del estado
  abreviatura    VARCHAR(5)  NOT NULL UNIQUE							-- Abreviatura oficial
);

-- ---------------------------------------------------------
-- Tabla: alumno
-- Contiene la información personal y académica básica de los alumnos inscritos en la institución.
-- ---------------------------------------------------------

CREATE TABLE alumno (
  numero_cuenta      INT PRIMARY KEY,				-- Número único del alumno
  nombre             VARCHAR(25) NOT NULL,			-- Nombre(s)
  apellido_paterno   VARCHAR(25) NOT NULL,			-- Apellido paterno
  apellido_materno   VARCHAR(25) NOT NULL,			-- Apellido materno
  curp               CHAR(18)    NOT NULL UNIQUE,	-- CURP del alumno
  telefono           CHAR(10)    NOT NULL,			-- Teléfono de contacto
  sexo               CHAR(1)     NOT NULL,			-- Sexo (M/F)
  correo_electronico VARCHAR(100) NOT NULL UNIQUE,	-- Correo institucional/personal
  fecha_nacimiento   DATE        NOT NULL,			-- Fecha de nacimiento
  foto_perfil        BYTEA NULL,                    -- Fotografía del alumno, imagen/binario (punto 7)
  id_entidad         INT         NOT NULL,			-- Entidad federativa de origen

-- Restricciones de validación
  CONSTRAINT ck_alumno_sexo CHECK (sexo IN ('M','F')),
  CONSTRAINT ck_alumno_tel  CHECK (telefono ~ '^[0-9]{10}$'),

-- Relación con entidad_federativa
  CONSTRAINT fk_alumno_entidad
    FOREIGN KEY (id_entidad)
    REFERENCES entidad_federativa(id_entidad)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);

-- ---------------------------------------------------------
-- Tabla: profesor
-- Almacena la información personal, laboral y salarial de los profesores que imparten cursos en la institución.
-- Incluye un campo JSONB para mantener un snapshot completo del registro del profesor. 
-- ---------------------------------------------------------

CREATE TABLE profesor (
  id_profesor        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,	-- Identificador único del profesor
  nombre             VARCHAR(25) NOT NULL,								-- Nombre(s)
  apellido_paterno   VARCHAR(25) NOT NULL,								-- Apellido paterno
  apellido_materno   VARCHAR(25) NOT NULL,								-- Apellido materno
  curp               CHAR(18)    NOT NULL UNIQUE,						-- CURP del profesor
  rfc                CHAR(13)    NOT NULL UNIQUE,						-- RFC fiscal
  telefono           CHAR(10)    NOT NULL,								-- Teléfono de contacto
  sexo               CHAR(1)     NOT NULL,								-- Sexo (M/F)
  correo_electronico VARCHAR(100) NOT NULL UNIQUE,						-- Correo electrónico
  fecha_nacimiento   DATE        NOT NULL,								-- Fecha de nacimiento
  sueldo             NUMERIC(10,2) NOT NULL,							-- Sueldo del profesor
  all_data_professor JSONB NOT NULL DEFAULT '{}'::jsonb,				-- Snapshot JSON del registro
  
  -- Restricciones de validación
  CONSTRAINT ck_profesor_sexo   CHECK (sexo IN ('M','F')),
  CONSTRAINT ck_profesor_tel    CHECK (telefono ~ '^[0-9]{10}$'),
  CONSTRAINT ck_profesor_sueldo CHECK (sueldo >= 0)
);



CREATE TABLE asignatura (
  clave_asignatura INT PRIMARY KEY,		-- Clave única de la asignatura
  nombre VARCHAR(80) NOT NULL UNIQUE	-- Nombre de la materia
);



CREATE TABLE grupo (
  id_grupo INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,	-- Identificador del grupo
  nombre_grupo CHAR(4) NOT NULL UNIQUE							-- Nombre o clave del grupo
);


CREATE TABLE tipo_curso (
  id_tipo_curso INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,	-- Identificador del tipo
  nombre_tipo   VARCHAR(40) NOT NULL UNIQUE							-- Nombre del tipo de curso
);

-- ---------------------------------------------------------
-- Tabla: nivel_semestre
-- Catálogo de niveles o semestres académicos (ej. Primero, Segundo, Tercero, etc).
-- Se hizo esta tabla mas que nada para evitar redunancia. 
-- ---------------------------------------------------------

CREATE TABLE nivel_semestre (
  id_nivel_semestre INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,	-- Identificador del nivel
  nombre_semestre   VARCHAR(12) NOT NULL UNIQUE							-- Nombre del semestre
);



CREATE TABLE periodo_academico (
  id_periodo     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,	-- Identificador del periodo
  periodo_nombre VARCHAR(8) NOT NULL UNIQUE,						-- Nombre del periodo
  fecha_inicio   DATE NOT NULL,										-- Fecha de inicio
  fecha_fin      DATE NOT NULL,										-- Fecha de fin
  
  -- Validación de rango de fechas
  CONSTRAINT ck_periodo_fechas CHECK (fecha_inicio < fecha_fin)
);


CREATE TABLE oferta_semestral (
  id_oferta_semestral INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,		-- Identificador de la oferta
  id_periodo          INT NOT NULL,											-- Periodo académico
  id_nivel_semestre   INT NOT NULL,											-- Nivel o semestre

-- Relación con periodo_academico
  CONSTRAINT fk_oferta_periodo
    FOREIGN KEY (id_periodo)
    REFERENCES periodo_academico(id_periodo)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,

-- Relación con nivel_semestre
  CONSTRAINT fk_oferta_nivel
    FOREIGN KEY (id_nivel_semestre)
    REFERENCES nivel_semestre(id_nivel_semestre)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,

-- Evita duplicar ofertas del mismo periodo y semestre
  CONSTRAINT uq_oferta_periodo_nivel UNIQUE (id_periodo, id_nivel_semestre)
);


-- ---------------------------------------------------------
-- Tabla: curso
-- Representa un curso específico (asignatura + profesor + grupo + semestre).
--
-- Campo adicional: inscritos_actual
--   - Agregamos este campo para llevar un contador del número de alumnos
--     inscritos en cada curso.
--   - Un trigger (trg_inscritos) se dispara cuando se inserta o elimina un
--     registro en alumno_curso y actualiza este contador automáticamente.
--   - El procedimiento sp_inscribir_alumno_cupo usa cupo_maximo e
--     inscritos_actual para validar que no se exceda el cupo cuando se intenta
--     inscribir a un alumno.
-- ---------------------------------------------------------


CREATE TABLE curso (
  id_curso            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,	-- Identificador del curso
  cupo_maximo         INT NOT NULL,										-- Cupo máximo permitido
  inscritos_actual    INT NOT NULL DEFAULT 0,							-- Alumnos inscritos actualmente
  id_profesor         INT NOT NULL,										-- Profesor a cargo
  clave_asignatura    INT NOT NULL,										-- Asignatura impartida
  id_oferta_semestral INT NOT NULL,										-- Oferta semestral
  id_tipo_curso       INT NOT NULL,										-- Tipo o modalidad del curso
  id_grupo            INT NOT NULL,										-- Grupo asignado

-- Restricciones de validación
  CONSTRAINT ck_curso_cupo     CHECK (cupo_maximo > 0),
  CONSTRAINT ck_curso_inscritos CHECK (inscritos_actual >= 0),

-- Relaciones con catálogos y entidades principales
  CONSTRAINT fk_curso_profesor
    FOREIGN KEY (id_profesor)
    REFERENCES profesor(id_profesor)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,

  CONSTRAINT fk_curso_asignatura
    FOREIGN KEY (clave_asignatura)
    REFERENCES asignatura(clave_asignatura)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,

  CONSTRAINT fk_curso_oferta
    FOREIGN KEY (id_oferta_semestral)
    REFERENCES oferta_semestral(id_oferta_semestral)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,

  CONSTRAINT fk_curso_tipo
    FOREIGN KEY (id_tipo_curso)
    REFERENCES tipo_curso(id_tipo_curso)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,

  CONSTRAINT fk_curso_grupo
    FOREIGN KEY (id_grupo)
    REFERENCES grupo(id_grupo)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);

-- ---------------------------------------------------------
-- Tabla: horario
-- Define los horarios disponibles para impartir cursos, incluyendo día de la semana y rango de horas.
-- ---------------------------------------------------------

CREATE TABLE horario (
  id_horario  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,		-- Identificador del horario
  dia         VARCHAR(10) NOT NULL,									-- Día de la semana
  hora_inicio TIME NOT NULL,										-- Hora de inicio
  hora_fin    TIME NOT NULL,										-- Hora de fin
  
  -- Validaciones de horario
  CONSTRAINT ck_horario_horas CHECK (hora_inicio < hora_fin),
  CONSTRAINT ck_horario_dia CHECK (dia IN ('Lunes','Martes','Miercoles','Jueves','Viernes','Sabado'))
);

-- ---------------------------------------------------------
-- Tabla: salon
-- Catálogo de salones físicos donde se imparten los cursos.
-- Esta tabla existe porque un curso puede tener varios salones y un salon puede tener varios cursos
-- Entonces se generaba mucha redundancia 
-- ---------------------------------------------------------

CREATE TABLE salon (
  id_salon INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,	-- Identificador del salón
  nombre_salon VARCHAR(20) NOT NULL UNIQUE						-- Nombre o clave del salón
);

-- ---------------------------------------------------------
-- Tabla: asignacion_curso 
-- es una tabla intermedia que relaciona
--       curso + horario + salón.
--     Cada fila significa: "el curso X se imparte en el salón Y en el horario Z".
--
-- Con la restricción UNIQUE (id_horario, id_salon) en `asignacion_curso`
-- evitamos que haya dos cursos al mismo tiempo en el mismo salón.
-- Además, permitimos que:
--   - un mismo curso pueda tener varios horarios/salones (varias filas),
--   - y un mismo salón se use en diferentes horarios sin empalmes.
-- ---------------------------------------------------------

CREATE TABLE asignacion_curso (
  id_asignacion_curso INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,	-- Identificador de la asignación
  id_horario INT NOT NULL,												-- Horario asignado
  id_curso   INT NOT NULL,												-- Curso asignado
  id_salon   INT NOT NULL,												-- Salón asignado

-- Relaciones
  CONSTRAINT fk_asig_horario FOREIGN KEY (id_horario)
    REFERENCES horario(id_horario)
    ON DELETE RESTRICT ON UPDATE CASCADE,

  CONSTRAINT fk_asig_curso FOREIGN KEY (id_curso)
    REFERENCES curso(id_curso)
    ON DELETE RESTRICT ON UPDATE CASCADE,

  CONSTRAINT fk_asig_salon FOREIGN KEY (id_salon)
    REFERENCES salon(id_salon)
    ON DELETE RESTRICT ON UPDATE CASCADE,

-- Evita que un salón tenga dos cursos al mismo horario
  CONSTRAINT uq_asig_horario_salon UNIQUE (id_horario, id_salon)
);

-- ---------------------------------------------------------
-- Tabla: alumno_curso
-- Registra la inscripción de alumnos a cursos y sus evaluaciones parciales.
--
-- Campo: estatus_evaluacion
--   - Indica en qué situación quedó la evaluación del alumno en ese curso.
--   - Usamos dos valores:
--       'REG' → Alumno regular (cursó normalmente).
--       'NP'  → No presentó / no terminó la materia.
--   - Por defecto es 'REG'.
--   - Cuando es 'NP', los triggers se encargan de limpiar las calificaciones
--     parciales y evitar que se calcule un promedio final.
-- ---------------------------------------------------------

CREATE TABLE alumno_curso (
  id_alumno_curso INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,	-- Identificador de la inscripción
  primer_parcial  NUMERIC(4,2) NULL,								-- Calificación primer parcial
  segundo_parcial NUMERIC(4,2) NULL,								-- Calificación segundo parcial
  tercer_parcial  NUMERIC(4,2) NULL,								-- Calificación tercer parcial
  estatus_evaluacion VARCHAR(3) NOT NULL DEFAULT 'REG',				-- Estatus de evaluación
  numero_cuenta   INT NOT NULL,										-- Alumno inscrito
  id_curso        INT NOT NULL,										-- Curso inscrito

-- Evita inscripciones duplicadas
  CONSTRAINT uq_alumno_curso UNIQUE (numero_cuenta, id_curso),

-- Validaciones de calificaciones
  CONSTRAINT ck_p1 CHECK (primer_parcial  IS NULL OR (primer_parcial  BETWEEN 0 AND 10)),
  CONSTRAINT ck_p2 CHECK (segundo_parcial IS NULL OR (segundo_parcial BETWEEN 0 AND 10)),
  CONSTRAINT ck_p3 CHECK (tercer_parcial  IS NULL OR (tercer_parcial  BETWEEN 0 AND 10)),
  CONSTRAINT ck_estatus_final CHECK (estatus_evaluacion IN ('REG','NP')),

-- Regla: si es NP no puede haber calificaciones
  CONSTRAINT ck_np_sin_notas CHECK (
    (estatus_evaluacion = 'REG')
    OR
    (estatus_evaluacion = 'NP'
      AND primer_parcial  IS NULL
      AND segundo_parcial IS NULL
      AND tercer_parcial  IS NULL)
  ),

-- Relaciones
  CONSTRAINT fk_ac_alumno FOREIGN KEY (numero_cuenta)
    REFERENCES alumno(numero_cuenta)
    ON DELETE RESTRICT ON UPDATE CASCADE,

  CONSTRAINT fk_ac_curso FOREIGN KEY (id_curso)
    REFERENCES curso(id_curso)
    ON DELETE RESTRICT ON UPDATE CASCADE
);



-- ---------------------------------------------------------
-- Tabla: plantel
-- Catálogo de planteles o sedes de la institución.
-- Esta tabla nada mas la agregamos para simular el historial del SIAE
-- Nada mas se agrego una facultad
-- ---------------------------------------------------------

CREATE TABLE plantel (
  clave_plantel INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 	-- Identificador del plantel
  nombre_plantel VARCHAR(150) NOT NULL UNIQUE						-- Nombre del plantel
);

-- ---------------------------------------------------------
-- Tabla: credito
-- Define los tipos de créditos académicos que puede obtener un alumno.
-- Esta tabla nada mas la agregamos para simular el historial del SIAE
-- ---------------------------------------------------------

CREATE TABLE credito (
  id_credito INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,		-- Identificador del crédito
  tipo_credito CHAR(3) NOT NULL,									-- Tipo (OBL/OPT)
  punto_credito INT NOT NULL,										-- Valor en créditos
  
  -- Validaciones
  CONSTRAINT ck_credito_puntos CHECK (punto_credito > 0),
  CONSTRAINT ck_credito_tipo   CHECK (tipo_credito IN ('OBL','OPT'))
);

-- ---------------------------------------------------------
-- Tabla: historial
-- Guarda el registro "oficial" de la calificación final de una inscripción
-- (lo que sería el historial académico / acta de calificaciones).
--
-- Campo: folio_acta
--   - Es un identificador alfanumérico del acta donde quedó registrada
--     la calificación del alumno en ese curso.
--   - Se genera automáticamente en los triggers con el formato
--     'AC' + id_alumno_curso con ceros a la izquierda (ej. 'AC00000017').
--   - Es UNIQUE, para que cada acta tenga un folio distinto y sea fácil
--     de localizar o referenciar en reportes.
-- ---------------------------------------------------------

CREATE TABLE historial (
  id_historial INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,	-- Identificador del historial
  folio_acta VARCHAR(10) NOT NULL UNIQUE,							-- Folio del acta
  id_alumno_curso INT NOT NULL,										-- Inscripción evaluada
  id_credito INT NOT NULL,											-- Crédito asociado
  clave_plantel INT NOT NULL,										-- Plantel correspondiente
  promedio_final NUMERIC(4,2) NULL,									-- Promedio final

-- Un historial por inscripción
  CONSTRAINT uq_hist_ac UNIQUE (id_alumno_curso),

  CONSTRAINT fk_hist_ac FOREIGN KEY (id_alumno_curso)
    REFERENCES alumno_curso(id_alumno_curso)
    ON DELETE RESTRICT ON UPDATE CASCADE,

  CONSTRAINT fk_hist_credito FOREIGN KEY (id_credito)
    REFERENCES credito(id_credito)
    ON DELETE RESTRICT ON UPDATE CASCADE,

  CONSTRAINT fk_hist_plantel FOREIGN KEY (clave_plantel)
    REFERENCES plantel(clave_plantel)
    ON DELETE RESTRICT ON UPDATE CASCADE
);


